Repository opensearch-project/neural-search, pull requests merged in 2022-12, with the labels that each got.

#72 Change the behavior when embedding fields not present
  src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
Labels: backport 2.x, backport 2.4

#79 Added release notes for 2.4.1 version
  release-notes/opensearch-neural-search.release-notes-2.4.1.0.md
Labels: backport 2.x, backport 2.4

#84 Use short-form MAINTAINERS.md.
  MAINTAINERS.md
Labels: backport 2.x

#88 Add filter option for query type
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
Labels: Enhancements, backport 2.x

#90 Updated the neural search plugin to implement the Extensible Plugin interface.
  build.gradle
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
Labels: v2.5.0
