Repository opensearch-project/neural-search, pull requests merged in 2022-10, with the labels that each got.

#28 Fix minor build.gradle issues
  build.gradle
Labels: backport 2.x

#40 Added windows support for CI.
  .github/workflows/CI.yml
Labels: enhancement, backport 2.x

#38 Add opensearch prefix to plugin name
  build.gradle
Labels: backport 2.x

#43 Fixing the locale changes from locale.default to locale.ROOT to fix the tests failing on windows.
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
Labels: v2.4.0, windows

#44 Fixing the locale changes from locale.default to locale.ROOT to fix the tests failing on windows.
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
Labels: bug, v2.4.0, windows

#36 Add integration tests for neural query
  build.gradle
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/plugin/TestUtils.java
  src/test/java/org/opensearch/neuralsearch/plugin/query/NeuralQueryIT.java
  src/test/resources/model/all-MiniLM-L6-v2.zip
  src/test/resources/processor/IndexMappings.json
  src/test/resources/processor/UploadModelRequestBody.json
Labels: backport 2.x
