Repository opensearch-project/neural-search, pull requests merged in 2023-10, with the labels that each got.

#365 [Backport 2.x] [Feature] Support for Default Model Id
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessor.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/visitor/NeuralSearchQueryVisitor.java
  src/main/java/org/opensearch/neuralsearch/util/NeuralSearchClusterUtil.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/visitor/NeuralSearchQueryVisitorTests.java
  src/test/java/org/opensearch/neuralsearch/util/NeuralSearchClusterTestUtils.java
  src/test/java/org/opensearch/neuralsearch/util/NeuralSearchClusterUtilTests.java
  src/test/resources/processor/IndexMappings.json
  src/test/resources/processor/SearchRequestPipelineConfiguration.json
Labels: v2.11.0

#359 Added Multimodal semantic search feature
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/TextEmbeddingProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/TextImageEmbeddingProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/constants/TestCommonConstants.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/TextImageEmbeddingProcessorFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/resources/processor/IndexMappings.json
  src/test/resources/processor/PipelineForTextImageEmbeddingProcessorConfiguration.json
Labels: Features, v2.11.0

#396 Fixed exception in Hybrid Query for one shard and multiple node
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowTests.java
Labels: backport 2.x, Bug Fixes, v2.11.0, backport 2.11

#392 Add 2.11 release note
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.11.0.0.md
Labels: backport 2.x, backport 2.11

#404 Fixed error for case when mltensor has data as null
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
Labels: skip-changelog, v2.11.0, backport 2.11

#407 [Backport 2.x]Add 2.11 release note (#392)
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.11.0.0.md
Labels: backport 2.11

#434 [Backport main] Added Multimodal semantic search feature
  build.gradle
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/NLPProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/TextEmbeddingProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/TextImageEmbeddingProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/constants/TestCommonConstants.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/TextImageEmbeddingProcessorFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/resources/processor/PipelineForTextImageEmbeddingProcessorConfiguration.json
Labels: Features, skip-changelog

#438 [bug fix] Fix async actions are left in neural_sparse query
  src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilderTests.java
Labels: backport 2.x, skip-changelog, v2.11.0

#416 Change query clause name to neural_sparse
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryIT.java
Labels: skip-changelog

#471 Adding developer guide
  DEVELOPER_GUIDE.md
Labels: backport 2.x, Maintenance, skip-changelog
