Repository opensearch-project/neural-search, pull requests merged in 2023-09, with the labels that each got.

#274 Made hybrid search active by default
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/settings/NeuralSearchSettings.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/query/OpenSearchQueryTestCase.java
Labels: Enhancements, backport 2.10

#277 Added release notes for 2.10 release
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.10.0.0.md
Labels: backport 2.x, skip-changelog, v2.10.0, backport 2.10

#287 [Backport 2.x] Added release notes for 2.10 release (#277)
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.10.0.0.md
Labels: skip-changelog, backport 2.10

#285 Fixed compilation errors after recent changes in ml-commons
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/resources/processor/CreateModelGroupRequestBody.json
Labels: Maintenance, skip-changelog

#292 [Upport main] Made hybrid search active by default by flipping feature flag default
  build.gradle
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/settings/NeuralSearchSettings.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/query/OpenSearchQueryTestCase.java
Labels: Enhancements, skip-changelog, v2.10.0

#344 Fix the compile error in [Backport/backport 333 to 2.x]
  src/test/java/org/opensearch/neuralsearch/common/BaseSparseEncodingIT.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessIT.java
Labels: skip-changelog

#345 Fix flaky integ test caused by latency of undeploy model
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
Labels: skip-changelog

#352 [Backport to 2.x] Fix flaky integ test caused by latency of undeploy …
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
Labels: skip-changelog

#356 Consumed latest changes from core, use QueryPhaseSearcherWrapper as parent class for Hybrid QPS
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
Labels: backport 2.x, Maintenance, v2.11.0

#337 [Feature] Support for Default Model Id
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessor.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/visitor/NeuralSearchQueryVisitor.java
  src/main/java/org/opensearch/neuralsearch/util/NeuralSearchClusterUtil.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/visitor/NeuralSearchQueryVisitorTests.java
  src/test/java/org/opensearch/neuralsearch/util/NeuralSearchClusterTestUtils.java
  src/test/java/org/opensearch/neuralsearch/util/NeuralSearchClusterUtilTests.java
  src/test/resources/processor/IndexMappings.json
  src/test/resources/processor/SearchRequestPipelineConfiguration.json
Labels: Features, backport 2.x, v2.11.0
