Repository opensearch-project/neural-search, pull requests merged in 2023-01, with the labels that each got.

#95 Updated MAINTAINERS.md format.
  MAINTAINERS.md
Labels: Documentation

#94 Remove unused MLPredict Transport action from src.
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/transport/MLPredictAction.java
  src/main/java/org/opensearch/neuralsearch/transport/MLPredictActionRequest.java
  src/main/java/org/opensearch/neuralsearch/transport/MLPredictActionResponse.java
  src/main/java/org/opensearch/neuralsearch/transport/MLPredictTransportAction.java
  src/test/java/org/opensearch/neuralsearch/constants/TestCommonConstants.java
  src/test/java/org/opensearch/neuralsearch/transport/MLPredictActionRequestTests.java
  src/test/java/org/opensearch/neuralsearch/transport/MLPredictActionResponseTests.java
  src/test/java/org/opensearch/neuralsearch/transport/MLPredictTransportActionTests.java
Labels: backport 2.x, Refactoring

#91 Add retry mechanism for neural search inference.
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/main/java/org/opensearch/neuralsearch/util/RetryUtil.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
Labels: Enhancements, backport 2.x, backport 2.5

#100 Add release notes for 25
  release-notes/opensearch-neural-search.release-notes-2.5.0.0.md
Labels: Documentation, backport 2.x, backport 2.5

#104 Update default setting for integ tests
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
Labels: backport 2.x, Infrastructure, backport 2.5
