Repository opensearch-project/neural-search, pull requests merged in 2023-08, with the labels that each got.

#241 Added Score Normalization and Combination feature
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ArithmeticMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/GeometricMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/HarmonicMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombinationFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombinationUtil.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/NormalizationProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizer.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQuery.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryScorer.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryWeight.java
  src/main/java/org/opensearch/neuralsearch/search/CompoundTopDocs.java
  src/main/java/org/opensearch/neuralsearch/search/HitsThresholdChecker.java
  src/main/java/org/opensearch/neuralsearch/search/HybridTopScoreDocCollector.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/test/java/org/opensearch/neuralsearch/TestUtils.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/ArithmeticMeanScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/BaseScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/GeometricMeanScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/HarmonicMeanScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/ScoreCombinationFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/NormalizationProcessorFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryScorerTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryWeightTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/OpenSearchQueryTestCase.java
  src/test/java/org/opensearch/neuralsearch/search/CompoundTopDocsTests.java
  src/test/java/org/opensearch/neuralsearch/search/HitsTresholdCheckerTests.java
  src/test/java/org/opensearch/neuralsearch/search/HybridTopScoreDocCollectorTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: Features, backport 2.x, v2.10.0

#243 Fixed compilation errors after refactoring in core Strings class
  src/test/java/org/opensearch/neuralsearch/ValidateDependentPluginInstallationIT.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
Labels: backport 2.x, skip-changelog

#246 Reworked feature flag usage for Hybrid search feature
  build.gradle
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ArithmeticMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/GeometricMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/HarmonicMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/NormalizationProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/settings/NeuralSearchSettings.java
  src/test/java/org/opensearch/neuralsearch/query/OpenSearchQueryTestCase.java
Labels: backport 2.x, skip-changelog

#249 Fixed compilation errors after refactoring in core
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
Labels: Maintenance, skip-changelog

#253 Porting different Backward incompatible changes happened in Core to 2.x branch
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/OpenSearchSecureRestTestCase.java
  src/test/java/org/opensearch/neuralsearch/ValidateDependentPluginInstallationIT.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
Labels: Maintenance, skip-changelog

#262 Fixed failing tests after ml-commons added model_group feature
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/resources/processor/CreateModelGroupRequestBody.json
  src/test/resources/processor/UploadModelRequestBody.json
Labels: Maintenance, skip-changelog

#259 Changed format for hybrid query results to a single list of scores with delimiter
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/CompoundTopDocs.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizer.java
  src/main/java/org/opensearch/neuralsearch/search/CompoundTopDocs.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/main/java/org/opensearch/neuralsearch/search/util/HybridSearchResultFormatUtil.java
  src/test/java/org/opensearch/neuralsearch/TestUtils.java
  src/test/java/org/opensearch/neuralsearch/processor/CompoundTopDocsTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
  src/test/java/org/opensearch/neuralsearch/search/util/HybridSearchResultFormatUtilTests.java
Labels: Enhancements, backport 2.x, backport 2.10
