Repository opensearch-project/neural-search, pull requests merged in 2023-04, with the labels that each got.

#147 [Backport 2.x] Fixed compilation errors after recent changes in core (#129)
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/OpenSearchSecureRestTestCase.java
  src/test/java/org/opensearch/neuralsearch/TestUtils.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
Labels: skip-changelog

#153 Add 2.7.0 Release Notes
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.7.0.0.md
Labels: backport 2.x, v2.7.0, skip-changelog, backport 2.7

#159 Dont wipe cluster settings after rest tests
  release-notes/opensearch-neural-search.release-notes-2.7.0.0.md
  src/test/java/org/opensearch/neuralsearch/OpenSearchSecureRestTestCase.java
Labels: backport 2.x, Infrastructure, skip-changelog, backport main

#164 [#1] Added badges and daily CI runs.
  .github/workflows/CI.yml
  README.md
Labels: Documentation, backport 2.x, skip-changelog
