Repository opensearch-project/neural-search, pull requests merged in 2023-07, with the labels that each got.

#208 Fix update document with knnn_vector size not matching issue
  src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
  src/test/resources/processor/CreateModelGroupRequestBody.json
Labels: skip-changelog

#209 Add 2.9.0 release note
  release-notes/opensearch-neural-search.release-notes-2.9.0.0.md
Labels: skip-changelog, v2.9.0

#219 Fix compilation errors, change core package name in import
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/TestUtils.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
Labels: backport 2.x, skip-changelog, v2.10.0

#214 Add feature flag for QueryPhaseSearcher
  build.gradle
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/TestUtils.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/OpenSearchQueryTestCase.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: skip-changelog

#232 Switch from XContentType to MediaType to fix compilation errors
  src/test/java/org/opensearch/neuralsearch/OpenSearchSecureRestTestCase.java
Labels: skip-changelog

#227 Adding search processor for score normalization and combination
  build.gradle
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ArithmeticMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombinationFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/NormalizationProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizer.java
  src/test/java/org/opensearch/neuralsearch/OpenSearchSecureRestTestCase.java
  src/test/java/org/opensearch/neuralsearch/TestUtils.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/NormalizationProcessorFactoryTests.java
Labels: skip-changelog

#235 Adding weights param for combination technique
  src/main/java/org/opensearch/neuralsearch/processor/combination/ArithmeticMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombinationFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/NormalizationProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationFactory.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/ArithmeticMeanScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/NormalizationProcessorFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
Labels: skip-changelog

#237 Fixing compilation errors after refactoring in core OpenSearch
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
Labels: skip-changelog

#236 Adding L2 norm technique
  src/main/java/org/opensearch/neuralsearch/processor/combination/HarmonicMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationFactory.java
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationFactoryTests.java
Labels: skip-changelog
