Repository opensearch-project/neural-search, pull requests merged in 2023-05, with the labels that each got.

#170 Baseline owners and maintainers
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#171 [Backport 2.x] Baseline owners and maintainers (#170)
  .github/CODEOWNERS
  MAINTAINERS.md
  src/test/java/org/opensearch/neuralsearch/common/BaseNeuralSearchIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/resources/processor/UploadModelRequestBody.json
Labels: skip-changelog

#169 Bump gradle version to 8.1.1
  CHANGELOG.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/resources/processor/UploadModelRequestBody.json
Labels: backport 2.x, Infrastructure

#167 Add Auto Release Workflow
  .github/workflows/auto-release.yml
Labels: backport 2.x, skip-changelog

#181 Update version to 2.8-SNAPSHOT
  build.gradle
Labels: skip-changelog, backport 2.8
