Repository opensearch-project/neural-search, pull requests merged in 2024-12, with the labels that each got.

#997 Add integration and unit tests for missing RRF coverage
  src/main/java/org/opensearch/neuralsearch/processor/RRFProcessor.java
  src/test/java/org/opensearch/neuralsearch/processor/RRFProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/RRFProcessorTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: skip-changelog

#1009 Change CI to use pull_request
  .github/workflows/CI.yml
Labels: security fix, skip-changelog, v2.19.0

#1014 [Feature to main] Explainability in hybrid query
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/CompoundTopDocs.java
  src/main/java/org/opensearch/neuralsearch/processor/ExplanationResponseProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowExecuteRequest.java
  src/main/java/org/opensearch/neuralsearch/processor/SearchShard.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ArithmeticMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/GeometricMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/HarmonicMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombinationUtil.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/CombinedExplanationDetails.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/DocIdAtSearchShard.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/ExplainableTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/ExplanationDetails.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/ExplanationPayload.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/ExplanationUtils.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/ExplanationResponseProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizer.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryWeight.java
  src/test/java/org/opensearch/neuralsearch/processor/CompoundTopDocsTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ExplanationPayloadProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/ArithmeticMeanScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/GeometricMeanScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/HarmonicMeanScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/explain/ExplanationUtilsTests.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/ExplanationResponseProcessorFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryExplainIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryWeightTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: backport 2.x, enhancement, v2.19.0, merge_from_feature_branch

#1026 Fixed failed test after knn added multiple inner hits feature
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
Labels: backport 2.x, Maintenance, skip-changelog, v2.19.0

#1013 Support of new k-NN query parameter, expand_nested
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/KnnRadialSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/KnnRadialSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
Labels: backport 2.x, enhancement, v2.19.0

#988 [Enhancement] Implement pruning for neural sparse search
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/NeuralSparseTwoPhaseProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/SparseEncodingProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/util/prune/PruneType.java
  src/main/java/org/opensearch/neuralsearch/util/prune/PruneUtils.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralSparseTwoPhaseProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralSparseTwoPhaseProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessIT.java
  src/test/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/SparseEncodingEmbeddingProcessorFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/util/prune/PruneTypeTests.java
  src/test/java/org/opensearch/neuralsearch/util/prune/PruneUtilsTests.java
  src/test/resources/processor/SparseEncodingPipelineConfigurationWithPrune.json
  src/test/resources/processor/UploadSparseEncodingModelRequestBody.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: backport 2.x, enhancement, v2.19.0

#1032 Remove mistakenly added code from HybridSearchIT.
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
Labels: backport 2.x, skip-changelog

#1034 Fix random total hits range for ExplanationPayloadProcessorTests.
  src/test/java/org/opensearch/neuralsearch/processor/ExplanationPayloadProcessorTests.java
Labels: backport 2.x, skip-changelog

#1037 Integrate explainability for hybrid query into RRF processor
  src/main/java/org/opensearch/neuralsearch/processor/AbstractScoreHybridizationProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/ExplanationResponseProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/RRFProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/RRFScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombinationFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/RRFNormalizationTechnique.java
  src/test/java/org/opensearch/neuralsearch/processor/AbstractScoreHybridizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ExplanationResponseProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/RRFProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/RRFScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/RRFNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryExplainIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: skip-changelog, hybrid search

#1041 Support empty string for fields in text embedding processor
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java
  src/test/java/org/opensearch/neuralsearch/processor/InferenceProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
Labels: backport 2.x, enhancement
