Repository opensearch-project/neural-search, pull requests merged in 2024-02, with the labels that each got.

#579 Distribution bundle bwc tests
  CHANGELOG.md
  build.gradle
  gradle.properties
  qa/restart-upgrade/build.gradle
  qa/rolling-upgrade/build.gradle
Labels: backport 2.x, Infrastructure

#584 Fixing same index name in NeuralQueryIT and HybridQueryIT
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
Labels: backport 2.x, skip-changelog

#585 Adding Varun(vibrantvarun) to list of CODEOWNERS
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#589 Update spotless and eclipse dependencies
  CHANGELOG.md
  build.gradle
Labels: backport 2.x, v2.12.0

#591 Added Reranker feature
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/RerankProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/RerankProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/RerankType.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/RescoringRerankProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/context/ContextSourceFetcher.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/context/DocumentContextSourceFetcher.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/context/QueryContextSourceFetcher.java
  src/main/java/org/opensearch/neuralsearch/query/ext/RerankSearchExtBuilder.java
  src/main/java/org/opensearch/neuralsearch/settings/NeuralSearchSettings.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/RerankProcessorFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/ext/RerankSearchExtBuilderTests.java
  src/test/resources/processor/RerankMLOpenSearchPipelineConfiguration.json
  src/test/resources/processor/UploadTextSimilarityModelRequestBody.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: Features, backport 2.x, v2.12.0

#593 Add release notes for 2.12.0 release
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.12.0.0.md
Labels: backport 2.x, v2.12.0, backport 2.12

#594 [Backport 2.x] Add release notes for 2.12.0 release
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.12.0.0.md
Labels: v2.12.0, backport 2.12

#578 Fix: typo for sparse encoding processor factory
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/factory/SparseEncodingProcessorFactory.java
Labels: backport 2.x

#602 Update bwc workflow to include 2.13.0-SNAPSHOT
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle.properties
Labels: backport 2.x, skip-changelog

#616 [Backport 2.x]Update bwc workflow to include 2.13.0-SNAPSHOT
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle.properties
Labels: skip-changelog
