Repository opensearch-project/neural-search, pull requests merged in 2024-04, with the labels that each got.

#663 Add support for local cache in hybrid query
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
Labels: backport 2.x, Bug Fixes, v2.14.0

#670 Allowing execution of hybrid query on index alias with filters
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/query/HybridQuery.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/main/java/org/opensearch/neuralsearch/util/HybridQueryUtil.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: backport 2.x, v2.14.0

#671 Cleanup integ tests by removing redundant model uploads
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
Labels: Infrastructure, skip-changelog

#673 Update bwc workflow to include 2.14.0-SNAPSHOT
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle.properties
Labels: backport 2.x, skip-changelog

#680 download security keys only if -Dsecurity.enabled==true
  build.gradle
Labels: backport 2.x, skip-changelog, backport 2.13

#683 Optimizing integ tests for less model upload calls
  CONTRIBUTING.md
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: backport 2.x, Maintenance, skip-changelog, v2.14.0

#691 [Backport 2.x] Optimizing integ tests for less model upload calls (#683)
  CONTRIBUTING.md
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/AbstractRollingUpgradeTestCase.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: skip-changelog

#632 Adding integ tests for scenario of hybrid query with aggregations
  .github/workflows/test_aggregations.yml
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  build.gradle
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BaseAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BucketAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/MetricAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/PipelineAggregationsWithHybridQueryIT.java
Labels: backport 2.x, Maintenance, v2.14.0

#693 enhancements: support neural_sparse query by tokens
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryIT.java
Labels: Enhancements, v2.14.0

#694 Add Advance Post Filter Integ Tests Scenarios
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/AbstractRestartUpgradeRestTestCase.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralQueryEnricherProcessorIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralSparseSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/SemanticSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/TextChunkingProcessorIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/AbstractRollingUpgradeTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralQueryEnricherProcessorIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralSparseSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/SemanticSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/TextChunkingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryPostFilterIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BaseAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BucketAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/MetricAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/PipelineAggregationsWithHybridQueryIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/OpenSearchSecureRestTestCase.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/AggregationsTestUtils.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/NeuralSearchClusterTestUtils.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: skip-changelog

#706 Replaced stream.findFirst by `for` loop for hybrid query
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryScorer.java
Labels: backport 2.x, v2.14.0, backport 2.13, hybrid query performance optimization

#709 [Backport 2.x] Add Advance Post Filter Integ Tests Scenarios (#694)
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/AbstractRestartUpgradeRestTestCase.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralQueryEnricherProcessorIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralSparseSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/SemanticSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/TextChunkingProcessorIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/AbstractRollingUpgradeTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralQueryEnricherProcessorIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralSparseSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/SemanticSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/TextChunkingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryPostFilterIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BaseAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BucketAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/MetricAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/PipelineAggregationsWithHybridQueryIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/OpenSearchSecureRestTestCase.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/AggregationsTestUtils.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/NeuralSearchClusterTestUtils.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: skip-changelog

#711 Removed map of subquery to subquery index in favor of storing index as part of DISI wrapper to improve hybrid query latencies by 20%
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryScorer.java
  src/main/java/org/opensearch/neuralsearch/search/HybridDisiWrapper.java
  src/test/java/org/opensearch/neuralsearch/search/HybridDisiWrapperTests.java
Labels: backport 2.x, v2.14.0, hybrid search, hybrid query performance optimization

#721 Add 2.14 release notes
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.14.0.0.md
Labels: backport 2.x, skip-changelog
