Repository opensearch-project/neural-search, pull requests merged in 2024-05, with the labels that each got.

#713 Fix: text chunking processor ingestion bug on multi-node cluster
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/TextChunkingProcessorIT.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/TextChunkingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/TextChunkingProcessorFactory.java
  src/test/java/org/opensearch/neuralsearch/processor/TextChunkingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/TextChunkingProcessorFactoryTests.java
Labels: backport 2.x, backport 2.13

#726 Fixed unit tests after core added new assertion for remote metadata in index settings
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: backport 2.x, skip-changelog, backport 2.14

#728 [Backport 2.x] Fixed unit tests after core added new assertion for remote metadata in index settings (#726)
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: skip-changelog

#727 [Backport 2.14] Fixed unit tests after core added new assertion for remote metadata in index settings (#726)
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: skip-changelog

#731 Pass empty QueryCollectorContext in case of hybrid query to improve latencies by 20%
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: backport 2.x, v2.15.0, hybrid search, hybrid query performance optimization

#734 Update release note for 2.14 release
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.14.0.0.md
Labels: backport 2.x, skip-changelog, backport 2.14

#733 Optimize parameter parsing in text chunking processor
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/TextChunkingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/ChunkerParameterParser.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/DelimiterChunker.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/FixedTokenLengthChunker.java
  src/test/java/org/opensearch/neuralsearch/processor/chunker/ChunkerParameterParserTests.java
  src/test/java/org/opensearch/neuralsearch/processor/chunker/DelimiterChunkerTests.java
  src/test/java/org/opensearch/neuralsearch/processor/chunker/FixedTokenLengthChunkerTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: backport 2.x

#753 Update bwc workflow to include 2.15.0-SNAPSHOT
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle.properties
Labels: Maintenance, skip-changelog

#746 Use lazy initialization for priority queue of hits and scores to improve latencies by 20%
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryScorer.java
  src/main/java/org/opensearch/neuralsearch/search/HybridTopScoreDocCollector.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryScorerTests.java
  src/test/java/org/opensearch/neuralsearch/search/HybridTopScoreDocCollectorTests.java
Labels: backport 2.x, performance, v2.15.0, hybrid search, hybrid query performance optimization

#757 Bug fix for total hits counts mismatch in hybrid query
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/search/HybridTopScoreDocCollector.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/search/HybridTopScoreDocCollectorTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: backport 2.x, Bug Fixes, v2.15.0

#748 Updating security reachout email
  SECURITY.md
Labels: backport 2.x, skip-changelog

#744 [FEATURE] Support batch ingestion in TextEmbeddingProcessor & SparseEncodingProcessor
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java
  src/test/java/org/opensearch/neuralsearch/processor/InferenceProcessorTestCase.java
  src/test/java/org/opensearch/neuralsearch/processor/InferenceProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
  src/test/resources/processor/bulk_item_template.json
  src/test/resources/processor/ingest_doc1.json
  src/test/resources/processor/ingest_doc2.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: backport 2.x

#765 Optimize the max score tracking in the Query Phase of Hybrid Search
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/search/HybridTopScoreDocCollector.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
Labels: backport 2.x, v2.15.0
