Repository opensearch-project/neural-search, pull requests merged in 2024-11, with the labels that each got.

#975 Fixed code coverage report
  .github/workflows/CI.yml
  codecov.yml
Labels: backport 2.x, Infrastructure, skip-changelog

#977 Refactored HybridQueryPhaseSearcherTests to remove knn specific classes
  codecov.yml
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: backport 2.x, skip-changelog

#980 Upgrade BWC version to 2.19
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle.properties
Labels: backport 2.x, Maintenance, skip-changelog

#983 Added 2.19 as next OS version (#980)
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle.properties
Labels: Maintenance, skip-changelog

#970 Explainability in hybrid query
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/CompoundTopDocs.java
  src/main/java/org/opensearch/neuralsearch/processor/ExplanationResponseProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowExecuteRequest.java
  src/main/java/org/opensearch/neuralsearch/processor/SearchShard.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ArithmeticMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/GeometricMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/HarmonicMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombinationUtil.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/CombinedExplanationDetails.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/DocIdAtSearchShard.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/ExplainableTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/ExplanationDetails.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/ExplanationPayload.java
  src/main/java/org/opensearch/neuralsearch/processor/explain/ExplanationUtils.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/ExplanationResponseProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizer.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryWeight.java
  src/test/java/org/opensearch/neuralsearch/processor/CompoundTopDocsTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ExplanationPayloadProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/ArithmeticMeanScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/GeometricMeanScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/combination/HarmonicMeanScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/explain/ExplanationUtilsTests.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/ExplanationResponseProcessorFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryExplainIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryWeightTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: Enhancements

#995 Update codecov to check during PR
  .github/workflows/CI.yml
  codecov.yml
Labels: Enhancements, backport 2.x, Infrastructure, skip-changelog

#999 Switch codecov to v3 as it requires python3.11 instead of node20
  .github/workflows/CI.yml
Labels: Enhancements, backport 2.x, Infrastructure, skip-changelog

#1002 Update security runs to also support AL2 on node20
  .github/workflows/test_aggregations.yml
  .github/workflows/test_security.yml
Labels: backport 2.x, skip-changelog

#998 Address inconsistent scoring in hybrid query results
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryScorer.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridTopScoreDocCollector.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryScorerTests.java
Labels: backport 2.x, Bug Fixes, v2.19.0
