Repository opensearch-project/neural-search, pull requests merged in 2024-01, with the labels that each got.

#531 Update Developer guide with steps to run BWC Test Suite
  DEVELOPER_GUIDE.md
  build.gradle
Labels: backport 2.x, skip-changelog

#494 Adding support for generic re-ranker interface and opensearch ml re-ranker for improving search relavancy.
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/RerankProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/RerankProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/RerankType.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/RescoringRerankProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/context/ContextSourceFetcher.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/context/DocumentContextSourceFetcher.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/context/QueryContextSourceFetcher.java
  src/main/java/org/opensearch/neuralsearch/query/ext/RerankSearchExtBuilder.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/RerankProcessorFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/ext/RerankSearchExtBuilderTests.java
  src/test/resources/processor/RerankMLOpenSearchPipelineConfiguration.json
  src/test/resources/processor/UploadTextSimilarityModelRequestBody.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: Features, v2.12.0

#535 Run Integ test in a secure opensearch cluster
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/test_security.yml
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  build.gradle
Labels: backport 2.x, Infrastructure

#543 Fixing pulling of security plugin to run integ tests in secure opensearch cluster
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/test_security.yml
  build.gradle
Labels: backport 2.x, skip-changelog

#541 Enable support for default model id on HybridQueryBuilder
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/OpenSearchQueryTestCase.java
Labels: backport 2.x, Bug Fixes

#551 Remove references to admin:admin
  DEVELOPER_GUIDE.md
  gradle/formatting.gradle
Labels: backport 2.x, skip-changelog

#565 Update GA to use latest JDK-21
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/test_security.yml
Labels: backport 2.x, skip-changelog

#569 [Backport 2.x]Update GA to use latest JDK-21
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/test_security.yml
Labels: skip-changelog

#559 Fix for Flaky test for issue 384
  CHANGELOG.md
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: backport 2.x, Bug Fixes, v2.12.0
