Repository opensearch-project/neural-search, pull requests merged in 2024-10, with the labels that each got.

#918 yuye-aws as the maintainer of neural-search
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#919 Revert "yuye-aws as the maintainer of neural-search"
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#920 adding Yuye Zhu as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#917 Added rescorer in hybrid query
  CHANGELOG.md
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/main/java/org/opensearch/neuralsearch/search/query/exception/HybridSearchRescoreQueryException.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridCollectorManagerTests.java
Labels: Enhancements, backport 2.x, v2.18.0

#927 Fixed unit test for neural query after recent knn change in rescore context
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: backport 2.x, Maintenance, skip-changelog

#913 Fix nested field missing sub embedding field
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java
  src/test/java/org/opensearch/neuralsearch/processor/InferenceProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
  src/test/resources/processor/IndexMappings.json
  src/test/resources/processor/ingest_doc1.json
  src/test/resources/processor/ingest_doc2.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: bug, backport 2.x, v2.18.0

#928 [documentation] Adds documentation to help fix local Lucene code errors
  DEVELOPER_GUIDE.md
Labels: skip-changelog

#953 Add Release Notes for 2.18.0.0
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.18.0.0.md
Labels: skip-changelog

#932 ByFieldRerank Processor (ReRankProcessor enhancement)
  DEVELOPER_GUIDE.md
  release-notes/opensearch-neural-search.release-notes-2.18.0.0.md
  src/main/java/org/opensearch/neuralsearch/processor/factory/RerankProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/ByFieldRerankProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/RerankProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/RerankType.java
  src/main/java/org/opensearch/neuralsearch/processor/util/ProcessorUtils.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/RerankProcessorFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/ByFieldRerankProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/ByFieldRerankProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/util/ProcessorUtilsTests.java
  src/test/resources/processor/ReRankByFieldPipelineConfiguration.json
Labels: Features, backport 2.x, skip-changelog, v2.18.0, backport 2.18

#956 Fixed incorrect document order for nested aggregations in hybrid query
  release-notes/opensearch-neural-search.release-notes-2.18.0.0.md
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryScorer.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/resources/processor/ingest_bulk.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: bug, backport 2.x, skip-changelog, backport 2.18

#959 [Backport 2.18] Fixed incorrect document order for nested aggregations in hybrid query
  release-notes/opensearch-neural-search.release-notes-2.18.0.0.md
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryScorer.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/resources/processor/ingest_bulk.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: skip-changelog

#966 Update maintainers.md by adding @ylwu-amzn and @jngz-es to emeritus
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#971 Nominate Minal Shah (minalsha) as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#972 [Backport 2.x] Nominate Minal Shah (minalsha) as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog
