Repository opensearch-project/neural-search, pull requests merged in 2024-07, with the labels that each got.

#802 [Part 2] Normalization Phase for Sorting
  src/main/java/org/opensearch/neuralsearch/processor/CompoundTopDocs.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/CombineScoresDto.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/search/util/HybridSearchSortUtil.java
  src/test/java/org/opensearch/neuralsearch/processor/CompoundTopDocsTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryPostFilterIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/MetricAggregationsWithHybridQueryIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: skip-changelog

#809 Update bwc workflow to include 2.16.0-SNAPSHOT
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle.properties
Labels: backport 2.x, skip-changelog

#810 Update bwc workflow to include 2.16.0-SNAPSHOT (#809)
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle.properties
Labels: skip-changelog

#814 [Enhancement] Adds method_parameters in neural search query to support ef_search
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/KnnRadialSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/KnnRadialSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  src/main/java/org/opensearch/neuralsearch/common/MinClusterVersionUtil.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/util/ProcessorDocumentUtils.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
Labels: Enhancements, Features, backport 2.x

#821 Fix linux build CI error due to action runner env upgrade node 20
  .github/workflows/CI.yml
  .github/workflows/test_aggregations.yml
  .github/workflows/test_security.yml
Labels: backport 2.x, Infrastructure, skip-changelog

#777 Neural sparse query two-phase search processor's bwc test
  CHANGELOG.md
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralSparseTwoPhaseProcessorIT.java
  qa/restart-upgrade/src/test/resources/processor/NeuralSparseTwoPhaseProcessorConfiguration.json
  qa/rolling-upgrade/build.gradle
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralSparseTwoPhaseProcessorIT.java
  qa/rolling-upgrade/src/test/resources/processor/NeuralSparseTwoPhaseProcessorConfiguration.json
Labels: Features

#811 Enable '.' for nested field in text embedding processor
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java
  src/test/java/org/opensearch/neuralsearch/processor/InferenceProcessorTestCase.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
  src/test/resources/processor/IndexMappings.json
  src/test/resources/processor/PipelineConfigurationWithNestedFieldsMapping.json
  src/test/resources/processor/ingest_doc3.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: Enhancements, backport 2.x, v2.16.0

#808 [Part 3] Concurrent segment search bug in Sorting
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridSearchCollector.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridTopFieldDocSortCollector.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridTopScoreDocCollector.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryFieldDocComparator.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryScoreDocsMerger.java
  src/main/java/org/opensearch/neuralsearch/search/query/TopDocsMerger.java
  src/main/java/org/opensearch/neuralsearch/search/util/HybridSearchResultFormatUtil.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryPostFilterIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BaseAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BucketAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/MetricAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/PipelineAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridCollectorManagerTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryScoreDocsMergerTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/TopDocsMergerTests.java
  src/test/java/org/opensearch/neuralsearch/search/util/HybridSearchResultFormatUtilTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: skip-changelog

#827 [Feature] Enable sorting and search_after features in hybrid search
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/CompoundTopDocs.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/CombineScoresDto.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/search/HitsThresholdChecker.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridSearchCollector.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridTopFieldDocSortCollector.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridTopScoreDocCollector.java
  src/main/java/org/opensearch/neuralsearch/search/collector/PagingFieldCollector.java
  src/main/java/org/opensearch/neuralsearch/search/collector/SimpleFieldCollector.java
  src/main/java/org/opensearch/neuralsearch/search/lucene/MultiLeafFieldComparator.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryFieldDocComparator.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryScoreDocsMerger.java
  src/main/java/org/opensearch/neuralsearch/search/query/TopDocsMerger.java
  src/main/java/org/opensearch/neuralsearch/search/util/HybridSearchResultFormatUtil.java
  src/main/java/org/opensearch/neuralsearch/search/util/HybridSearchSortUtil.java
  src/test/java/org/opensearch/neuralsearch/processor/CompoundTopDocsTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryPostFilterIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/MetricAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/search/HybridTopFieldDocSortCollectorTests.java
  src/test/java/org/opensearch/neuralsearch/search/HybridTopScoreDocCollectorTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridCollectorManagerTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryScoreDocsMergerTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/TopDocsMergerTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: Enhancements, backport 2.x, v2.16.0

#834 Fix KNN SpaceType.getVectorSimilarityFunction renamed issue
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: backport 2.x, skip-changelog

#838 Set neural-search plugin 3.0.0 baseline JDK version to JDK-21
  CHANGELOG.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  qa/build.gradle
Labels: backport 2.x, enhancement

#795 Fix: correct gradle file function name and comment
  CHANGELOG.md
  qa/build.gradle
  qa/restart-upgrade/build.gradle
  qa/rolling-upgrade/build.gradle
Labels: backport 2.x

#823 Update PULL_REQUEST_TEMPLATE to include an API spec change in the checklist.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: backport 2.x, Infrastructure, skip-changelog

#851 Add triage.md based off of security
  TRIAGING.md
Labels: backport 2.x, skip-changelog
