Repository opensearch-project/neural-search, pull requests merged in 2024-03, with the labels that each got.

#477 Handle case with nested list of objects
  src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
  src/test/resources/processor/IndexMappings.json
  src/test/resources/processor/PipelineConfiguration.json
Labels: skip-changelog

#624 Fix runtime exceptions in hybrid query for case when sub-query scorer return TwoPhase iterator that is incompatible with DISI iterator
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/query/HybridQuery.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryScorer.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryWeight.java
  src/main/java/org/opensearch/neuralsearch/query/HybridScoreBlockBoundaryPropagator.java
  src/main/java/org/opensearch/neuralsearch/search/HybridTopScoreDocCollector.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridAggregationProcessor.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryScorerTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridScoreBlockBoundaryPropagatorTests.java
  src/test/java/org/opensearch/neuralsearch/search/HybridTopScoreDocCollectorTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridAggregationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridCollectorManagerTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: backport 2.x, Bug Fixes, v2.13.0

#630 Adding aggregations in hybrid query
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridAggregationProcessor.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/main/java/org/opensearch/neuralsearch/util/HybridQueryUtil.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
  src/test/java/org/opensearch/neuralsearch/util/AggregationsTestUtils.java
  src/test/java/org/opensearch/neuralsearch/util/HybridQueryUtilTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: Features, backport 2.x, v2.13.0

#631 [Backport 2.x] Adding aggregations in hybrid query (#630)
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridAggregationProcessor.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/main/java/org/opensearch/neuralsearch/util/HybridQueryUtil.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
  src/test/java/org/opensearch/neuralsearch/util/AggregationsTestUtils.java
  src/test/java/org/opensearch/neuralsearch/util/HybridQueryUtilTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: v2.13.0

#634 Fix Failing build due to slf4j from k-NN Plugin
  build.gradle
  qa/build.gradle
Labels: backport 2.x, skip-changelog

#633 Support for post filter in hybrid query
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridCollectorManagerTests.java
Labels: backport 2.x, v2.13.0

#614 [FEATURE] support default model id in neural_sparse query
  CHANGELOG.md
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralQueryEnricherProcessorIT.java
  qa/restart-upgrade/src/test/resources/processor/SearchRequestPipelineConfiguration.json
  qa/rolling-upgrade/build.gradle
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralQueryEnricherProcessorIT.java
  qa/rolling-upgrade/src/test/resources/processor/SearchRequestPipelineConfiguration.json
  src/main/java/org/opensearch/neuralsearch/query/ModelInferenceQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/visitor/NeuralSearchQueryVisitor.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/visitor/NeuralSearchQueryVisitorTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: backport 2.x, v2.13.0

#638 fix build.gradle to excludes neural_query_enricher neural sparse search in testRollingUpgrade
  qa/rolling-upgrade/build.gradle
Labels: skip-changelog

#639 Add knn field space type to fix unit tests
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
Labels: backport 2.x, Maintenance, skip-changelog, v2.13.0

#645 fix: the import error in integration test from [Backport/backport 607 to 2.x]
  src/test/java/org/opensearch/neuralsearch/processor/TextChunkingProcessorIT.java
Labels: skip-changelog

#650 adding maintainer @zhichao-aws
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog
