Repository opensearch-project/neural-search, pull requests merged in 2024-08, with the labels that each got.

#855 Fix package change from k-nn
  src/main/java/org/opensearch/neuralsearch/common/MinClusterVersionUtil.java
  src/test/java/org/opensearch/neuralsearch/NeuralSearchTests.java
Labels: backport 2.x, Maintenance, skip-changelog

#861 Fix package change from k-NN
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: bug, backport 2.x, skip-changelog

#868 Upgrade BWC version and fix neural search build
  .github/workflows/backwards_compatibility_tests_workflow.yml
  TRIAGING.md
  gradle.properties
  src/test/java/org/opensearch/neuralsearch/ValidateDependentPluginInstallationIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: backport 2.x, skip-changelog

#869 Fix neural search build & increment OS version to 2.17
  .github/workflows/backwards_compatibility_tests_workflow.yml
  TRIAGING.md
  build.gradle
  gradle.properties
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/test/java/org/opensearch/neuralsearch/ValidateDependentPluginInstallationIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
Labels: skip-changelog

#852 Remove batch_size of bulk API from tests & refactor BWC version check
  CHANGELOG.md
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/AbstractRestartUpgradeRestTestCase.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/BatchIngestionIT.java
  qa/rolling-upgrade/build.gradle
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/AbstractRollingUpgradeTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/BatchIngestionIT.java
  qa/rolling-upgrade/src/test/resources/processor/PipelineForSparseEncodingProcessorConfiguration.json
  src/test/java/org/opensearch/neuralsearch/processor/TextChunkingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/resources/processor/PipelineConfiguration.json
  src/test/resources/processor/SparseEncodingPipelineConfiguration.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: skip-changelog
