Repository opensearch-project/neural-search, pull requests merged in 2024-06, with the labels that each got.

#747 [Feature] Neural Sparse Query Two Phase Search pipeline
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/NeuralSparseTwoPhaseProcessor.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralSparseTwoPhaseProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralSparseTwoPhaseProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilderTests.java
  src/test/resources/processor/NeuralSparseTwoPhaseProcessorConfiguration.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: Features, v2.15.0

#770 Disable memory circuit breaker for integ tests
  CHANGELOG.md
  build.gradle
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BaseAggregationsWithHybridQueryIT.java
Labels: backport 2.x, Infrastructure, v2.15.0

#779 Remove parallelization of get hybridscores
  src/main/java/org/opensearch/neuralsearch/executors/HybridQueryScoresCollectionManager.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryScorer.java
Labels: skip-changelog

#781 Implement parallel execution of sub-queries for hybrid search
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/executors/HybridQueryExecutor.java
  src/main/java/org/opensearch/neuralsearch/executors/HybridQueryExecutorCollector.java
  src/main/java/org/opensearch/neuralsearch/executors/HybridQueryExecutorCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/executors/HybridQueryRewriteCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/executors/HybridQueryScoreSupplierCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQuery.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryWeight.java
  src/test/java/org/opensearch/neuralsearch/executors/HybridQueryExecutorIT.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
Labels: backport 2.x, v2.15.0

#784 Add release notes
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.15.0.0.md
Labels: backport 2.x, skip-changelog, v2.15.0

#801 Fix jdk version for CI test secure cluster action
  .github/workflows/test_security.yml
Labels: Maintenance, skip-changelog

#800 Fix for missing HybridQuery results when concurrent segment search is enabled
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryScoreDocsMerger.java
  src/main/java/org/opensearch/neuralsearch/search/query/TopDocsMerger.java
  src/main/java/org/opensearch/neuralsearch/search/util/HybridSearchResultFormatUtil.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryPostFilterIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BaseAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BucketAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/MetricAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/PipelineAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridCollectorManagerTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryScoreDocsMergerTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/TopDocsMergerTests.java
  src/test/java/org/opensearch/neuralsearch/search/util/HybridSearchResultFormatUtilTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: bug, backport 2.x, v2.16.0, hybrid search

#806 Fix jdk version for CI test secure cluster action (#801)
  .github/workflows/test_security.yml
Labels: skip-changelog

#797 [Part 1] Collector for Sorting Results
  src/main/java/org/opensearch/neuralsearch/search/HitsThresholdChecker.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridTopFieldDocSortCollector.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridTopScoreDocCollector.java
  src/main/java/org/opensearch/neuralsearch/search/collector/PagingFieldCollector.java
  src/main/java/org/opensearch/neuralsearch/search/collector/SimpleFieldCollector.java
  src/main/java/org/opensearch/neuralsearch/search/lucene/MultiLeafFieldComparator.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/search/util/HybridSearchResultFormatUtil.java
  src/main/java/org/opensearch/neuralsearch/util/ProcessorDocumentUtils.java
  src/test/java/org/opensearch/neuralsearch/search/HybridTopFieldDocSortCollectorTests.java
  src/test/java/org/opensearch/neuralsearch/search/HybridTopScoreDocCollectorTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridCollectorManagerTests.java
Labels: skip-changelog
