Repository opensearch-project/neural-search, pull requests merged in 2024-09, with the labels that each got.

#877 Fixed merge logic for multiple shards case
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/search/query/TopDocsMerger.java
  src/test/java/org/opensearch/neuralsearch/search/query/TopDocsMergerTests.java
Labels: bug, backport 2.x, backport 2.17

#867 Removing code to cut search results of hybrid search in the priority queue
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridTopScoreDocCollector.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryPostFilterIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/MetricAggregationsWithHybridQueryIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: backport 2.x, skip-changelog, backport 2.17

#882 Add release notes for 2.17
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.17.0.0.md
Labels: backport 2.x, skip-changelog, backport 2.17

#885 Adds rescore parameter in neural search
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/KnnRadialSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/KnnRadialSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
Labels: backport 2.x

#889 Corrects release notes for 2.17 for rescore enhancement
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.17.0.0.md
Labels: backport 2.x, skip-changelog, backport 2.17

#892 Increase timeout for cluster status call in BWC
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: Infrastructure, skip-changelog

#900 Reduce unnecessary duplication of changelog verifier GHA runs
  .github/workflows/changelog_verifier.yml
Labels: backport 2.x, skip-changelog

#898 Add coverage for NeuralSearch class
  .gitignore
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
Labels: backport 2.x, Maintenance, skip-changelog

#908 [chore]: bump developer guide java version
  DEVELOPER_GUIDE.md
Labels: skip-changelog

#916 Upgrade BWC version to 2.18
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle.properties
Labels: Maintenance, skip-changelog
