Repository opensearch-project/neural-search, pull requests merged in 2025-08, with the labels that each got.

#1505 Load for model to load for ITs
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
Labels: autocut, skip-changelog, v3.2.0

#1509 bump up commons-lang3 version
  build.gradle
Labels: skip-changelog, backport 3.2

#1502 Add basic classes for seismic algorithm
  src/main/java/org/opensearch/neuralsearch/sparse/accessor/ClusteredPosting.java
  src/main/java/org/opensearch/neuralsearch/sparse/accessor/ClusteredPostingReader.java
  src/main/java/org/opensearch/neuralsearch/sparse/accessor/ClusteredPostingWriter.java
  src/main/java/org/opensearch/neuralsearch/sparse/accessor/SparseVectorForwardIndex.java
  src/main/java/org/opensearch/neuralsearch/sparse/accessor/SparseVectorReader.java
  src/main/java/org/opensearch/neuralsearch/sparse/accessor/SparseVectorWriter.java
  src/main/java/org/opensearch/neuralsearch/sparse/common/ArrayIterator.java
  src/main/java/org/opensearch/neuralsearch/sparse/common/CombinedIterator.java
  src/main/java/org/opensearch/neuralsearch/sparse/common/DocWeightIterator.java
  src/main/java/org/opensearch/neuralsearch/sparse/common/IteratorWrapper.java
  src/main/java/org/opensearch/neuralsearch/sparse/common/MergeStateFacade.java
  src/main/java/org/opensearch/neuralsearch/sparse/common/PredicateUtils.java
  src/main/java/org/opensearch/neuralsearch/sparse/common/SparseConstants.java
  src/main/java/org/opensearch/neuralsearch/sparse/common/ValueEncoder.java
  src/main/java/org/opensearch/neuralsearch/sparse/data/DocWeight.java
  src/main/java/org/opensearch/neuralsearch/sparse/data/DocumentCluster.java
  src/main/java/org/opensearch/neuralsearch/sparse/data/PostingClusters.java
  src/main/java/org/opensearch/neuralsearch/sparse/data/SparseVector.java
  src/main/java/org/opensearch/neuralsearch/sparse/quantization/ByteQuantizer.java
  src/test/java/org/opensearch/neuralsearch/sparse/AbstractSparseTestBase.java
  src/test/java/org/opensearch/neuralsearch/sparse/TestsPrepareUtils.java
  src/test/java/org/opensearch/neuralsearch/sparse/common/ArrayIteratorTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/common/CombinedIteratorTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/common/IteratorWrapperTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/common/MergeStateFacadeTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/common/PredicateUtilsTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/common/ValueEncoderTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/data/DocWeightTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/data/DocumentClusterTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/data/PostingClustersTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/data/SparseVectorTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/quantization/ByteQuantizerTests.java
Labels: skip-changelog

#1504 Disable ML-Commons disk circuit breaker in tests
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: bug, skip-changelog

#1503 Fix flaky test in HybridQueryAggregationsIT
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: skip-changelog, flaky-test, backport 3.2

#1514 Add clustering algorithm and field mapper for seismic
  build.gradle
  src/main/java/org/opensearch/neuralsearch/sparse/algorithm/ClusterTrainingExecutor.java
  src/main/java/org/opensearch/neuralsearch/sparse/algorithm/ClusteringAlgorithm.java
  src/main/java/org/opensearch/neuralsearch/sparse/algorithm/PostingsProcessingUtils.java
  src/main/java/org/opensearch/neuralsearch/sparse/algorithm/SparseAlgoType.java
  src/main/java/org/opensearch/neuralsearch/sparse/algorithm/SparseAlgorithm.java
  src/main/java/org/opensearch/neuralsearch/sparse/algorithm/seismic/RandomClusteringAlgorithm.java
  src/main/java/org/opensearch/neuralsearch/sparse/algorithm/seismic/Seismic.java
  src/main/java/org/opensearch/neuralsearch/sparse/algorithm/seismic/SeismicPostingClusterer.java
  src/main/java/org/opensearch/neuralsearch/sparse/data/DocWeight.java
  src/main/java/org/opensearch/neuralsearch/sparse/data/DocumentCluster.java
  src/main/java/org/opensearch/neuralsearch/sparse/mapper/MethodComponentContext.java
  src/main/java/org/opensearch/neuralsearch/sparse/mapper/SparseMethodContext.java
  src/main/java/org/opensearch/neuralsearch/sparse/mapper/SparseTokensField.java
  src/main/java/org/opensearch/neuralsearch/sparse/mapper/SparseTokensFieldMapper.java
  src/main/java/org/opensearch/neuralsearch/sparse/mapper/SparseTokensFieldType.java
  src/test/java/org/opensearch/neuralsearch/sparse/algorithm/ClusterTrainingExecutorTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/algorithm/PostingsProcessingUtilsTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/algorithm/seismic/RandomClusteringAlgorithmTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/algorithm/seismic/SeismicPostingClustererAlgorithmTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/algorithm/seismic/SeismicTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/data/DocWeightTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/data/DocumentClusterTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/mapper/MethodComponentContextTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/mapper/SparseMethodContextTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/mapper/SparseTokensFieldMapperTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/mapper/SparseTokensFieldTests.java
  src/test/java/org/opensearch/neuralsearch/sparse/mapper/SparseTokensFieldTypeTests.java
Labels: skip-changelog
