Repository opensearch-project/neural-search, pull requests merged in 2025-07, with the labels that each got.

#1427 Handle remote dense model properly during mapping transform
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/mappingtransformer/SemanticInfoConfigBuilder.java
  src/main/java/org/opensearch/neuralsearch/mappingtransformer/TextEmbeddingInfo.java
  src/test/java/org/opensearch/neuralsearch/mappingtransformer/SemanticInfoConfigBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/mappingtransformer/SemanticMappingTransformerIT.java
  src/test/java/org/opensearch/neuralsearch/mappingtransformer/SemanticMappingTransformerTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryIT.java
  src/test/resources/mappingtransformer/CreateConnectorRequestBody.json
  src/test/resources/mappingtransformer/RegisterRemoteDenseModelRequestBody.json
  src/test/resources/mappingtransformer/SemanticIndexMappings.json
  src/test/resources/mappingtransformer/expectedIndexMappingWithRemoteDenseModel.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: bug, v3.2.0

#1430 Eliminate non-deterministic behavior in scoring for unit test
  src/test/java/org/opensearch/neuralsearch/search/query/HybridCollectorManagerTests.java
Labels: skip-changelog

#1420 Support configuring the auto-generated knn_vector field through the semantic field.
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/constants/SemanticFieldConstants.java
  src/main/java/org/opensearch/neuralsearch/constants/SemanticInfoFieldConstants.java
  src/main/java/org/opensearch/neuralsearch/mapper/SemanticFieldMapper.java
  src/main/java/org/opensearch/neuralsearch/mapper/dto/SemanticParameters.java
  src/main/java/org/opensearch/neuralsearch/mappingtransformer/SemanticInfoConfigBuilder.java
  src/main/java/org/opensearch/neuralsearch/mappingtransformer/SemanticMappingTransformer.java
  src/main/java/org/opensearch/neuralsearch/util/SemanticMappingUtils.java
  src/test/java/org/opensearch/neuralsearch/mapper/SemanticFieldMapperTests.java
  src/test/java/org/opensearch/neuralsearch/mappingtransformer/SemanticInfoConfigBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/mappingtransformer/SemanticMappingTransformerTests.java
  src/test/java/org/opensearch/neuralsearch/processor/semantic/SemanticFieldProcessorIT.java
  src/test/resources/processor/semantic/SemanticIndexMappingsForDense.json
  src/test/resources/processor/semantic/SemanticIndexMappingsForDenseWithChunking.json
Labels: enhancement

#1435 Fix HybridCollectorManagerTests for a core change.
  src/test/java/org/opensearch/neuralsearch/search/query/HybridCollectorManagerTests.java
Labels: skip-changelog

#1437 Fix flakey unit tests.
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
Labels: skip-changelog

#1432 Handle a hybrid query extended with DLS rules by the security plugin
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/query/HybridQuery.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/main/java/org/opensearch/neuralsearch/util/HybridQueryUtil.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
  src/test/java/org/opensearch/neuralsearch/util/HybridQueryUtilTests.java
Labels: bug

#1448 refactor bwc tests to find model ID in index for semantic field
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/SemanticFieldIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/SemanticFieldIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseUpgradeTestCase.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: skip-changelog

#1436 Updated gradle and java version to 24
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/test_aggregations.yml
  .github/workflows/test_security.yml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  src/main/plugin-metadata/plugin-security.policy
Labels: skip-changelog

#1431 [Feature] Add upper bound parameter for min_max normalization technique
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/bounds/BoundMode.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/bounds/LowerBound.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/bounds/ScoreBound.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/bounds/UpperBound.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/bounds/BoundModeTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/bounds/LowerBoundTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/bounds/UpperBoundTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: enhancement

#1457 Fixed how bitset works for custom bulk scorer in hybrid query
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStreamTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryWindowBoundaryIT.java
Labels: Bug Fixes, skip-changelog, v3.2.0

#1446 Support configuring the chunking strategies through the semantic field.
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/mapper/SemanticFieldMapper.java
  src/main/java/org/opensearch/neuralsearch/mapper/dto/ChunkingConfig.java
  src/main/java/org/opensearch/neuralsearch/mapper/dto/SemanticParameters.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/Chunker.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/ChunkerValidatorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/DelimiterChunker.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/FixedCharLengthChunker.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/FixedTokenLengthChunker.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/Parser.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/Validator.java
  src/main/java/org/opensearch/neuralsearch/processor/dto/SemanticFieldInfo.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/SemanticFieldProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/semantic/SemanticFieldProcessor.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/util/SemanticMappingUtils.java
  src/test/java/org/opensearch/neuralsearch/mapper/SemanticFieldMapperTests.java
  src/test/java/org/opensearch/neuralsearch/mapper/dto/ChunkingConfigTests.java
  src/test/java/org/opensearch/neuralsearch/processor/chunker/DelimiterChunkerTests.java
  src/test/java/org/opensearch/neuralsearch/processor/chunker/FixedCharLengthChunkerTests.java
  src/test/java/org/opensearch/neuralsearch/processor/chunker/FixedTokenLengthChunkerTests.java
  src/test/java/org/opensearch/neuralsearch/processor/dto/SemanticFieldInfoTests.java
  src/test/java/org/opensearch/neuralsearch/processor/semantic/SemanticFieldProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/semantic/SemanticFieldProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderRewriteTests.java
  src/test/resources/processor/semantic/SemanticIndexMappingsWithComplexChunking.json
  src/test/resources/processor/semantic/ingest_doc4.json
Labels: enhancement
