Repository opensearch-project/neural-search, pull requests merged in 2025-04, with the labels that each got.

#1254 Support custom tags in semantic highlighter
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/highlight/SemanticHighlighter.java
  src/main/java/org/opensearch/neuralsearch/highlight/SemanticHighlighterEngine.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/test/java/org/opensearch/neuralsearch/highlight/SemanticHighlighterEngineTests.java
  src/test/java/org/opensearch/neuralsearch/highlight/SemanticHighlighterIT.java
  src/test/java/org/opensearch/neuralsearch/highlight/SemanticHighlighterTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: Features, v3.0.0

#1252 Added release notes for 3.0 beta1
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-3.0.0.0-beta1.md
Labels: release, Maintenance, Infrastructure, v3.0.0

#1259 Update semantic highlighter test model
  src/test/resources/highlight/UploadSentenceHighlightingModelRequestBody.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: skip-changelog, v3.0.0

#1257 Fix the edge case when the value of a fieldMap key in ingestDocument is empty String
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessor.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorTests.java
Labels: bug, v3.1.0

#1268 Hybrid query should call rewrite before creating weight
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryWeight.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
Labels: skip-changelog

#1265 Support phasing off SecurityManager usage in favor of Java Agent
  build.gradle
  qa/build.gradle
  src/main/plugin-metadata/plugin-security.policy
Labels: skip-changelog

#1272 Fix multi nodes transport issue on originalQueryText
  src/main/java/org/opensearch/neuralsearch/common/MinClusterVersionUtil.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralKNNQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralKNNQueryBuilderTests.java
Labels: skip-changelog

#1225 Add semantic field mapper.
  CHANGELOG.md
  build.gradle
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/HybridSearchWithRescoreIT.java
  src/main/java/org/opensearch/neuralsearch/constants/MappingConstants.java
  src/main/java/org/opensearch/neuralsearch/constants/SemanticFieldConstants.java
  src/main/java/org/opensearch/neuralsearch/mapper/SemanticFieldMapper.java
  src/main/java/org/opensearch/neuralsearch/mapper/dto/SemanticParameters.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/settings/NeuralSearchSettings.java
  src/main/java/org/opensearch/neuralsearch/util/FeatureFlagUtil.java
  src/test/java/org/opensearch/neuralsearch/mapper/SemanticFieldMapperTestUtil.java
  src/test/java/org/opensearch/neuralsearch/mapper/SemanticFieldMapperTests.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ExplanationResponseProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/OpenSearchQueryTestCase.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: Enhancements, neural-search

#1277 Fixed score value as null for single shard for sorting
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/CombineScoresDto.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java
Labels: bug, v3.1.0

#1285 Add WithFieldName implementation to QueryBuilders
  src/main/java/org/opensearch/neuralsearch/query/NeuralKNNQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java
Labels: skip-changelog, enhancement

#1292 Remove beta1 qualifier
  build.gradle
Labels: release, skip-changelog, backport main, v3.0.0

#1295 Fix for merging scoreDocs when totalHits are greater than 1 and fieldDocs are 0
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryScoreDocsMerger.java
Labels: skip-changelog, backport 3.0

#1287 add release notes for 3.0
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-3.0.0.0.md
Labels: skip-changelog, backport 3.0
