Repository opensearch-project/neural-search, pull requests merged in 2025-03, with the labels that each got.

#1214 Adding release notes for 3.0-alpha1
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-3.0.0.0-alpha1.md
Labels: Maintenance, v3.0.0

#1223 Use latest json-smart lib
  build.gradle
  qa/build.gradle
Labels: Maintenance, skip-changelog, v3.0.0

#1208 [Feature branch] Add Neural Stats API
  CHANGELOG.md
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/RestNeuralStatsActionIT.java
  qa/rolling-upgrade/build.gradle
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/RestNeuralStatsActionIT.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java
  src/main/java/org/opensearch/neuralsearch/rest/RestNeuralStatsAction.java
  src/main/java/org/opensearch/neuralsearch/settings/NeuralSearchSettings.java
  src/main/java/org/opensearch/neuralsearch/settings/NeuralSearchSettingsAccessor.java
  src/main/java/org/opensearch/neuralsearch/stats/NeuralStatsInput.java
  src/main/java/org/opensearch/neuralsearch/stats/common/StatName.java
  src/main/java/org/opensearch/neuralsearch/stats/common/StatSnapshot.java
  src/main/java/org/opensearch/neuralsearch/stats/common/StatType.java
  src/main/java/org/opensearch/neuralsearch/stats/events/EventStat.java
  src/main/java/org/opensearch/neuralsearch/stats/events/EventStatName.java
  src/main/java/org/opensearch/neuralsearch/stats/events/EventStatType.java
  src/main/java/org/opensearch/neuralsearch/stats/events/EventStatsManager.java
  src/main/java/org/opensearch/neuralsearch/stats/events/TimestampedEventStat.java
  src/main/java/org/opensearch/neuralsearch/stats/events/TimestampedEventStatSnapshot.java
  src/main/java/org/opensearch/neuralsearch/stats/info/CountableInfoStatSnapshot.java
  src/main/java/org/opensearch/neuralsearch/stats/info/InfoStatName.java
  src/main/java/org/opensearch/neuralsearch/stats/info/InfoStatType.java
  src/main/java/org/opensearch/neuralsearch/stats/info/InfoStatsManager.java
  src/main/java/org/opensearch/neuralsearch/stats/info/SettableInfoStatSnapshot.java
  src/main/java/org/opensearch/neuralsearch/transport/NeuralStatsAction.java
  src/main/java/org/opensearch/neuralsearch/transport/NeuralStatsNodeRequest.java
  src/main/java/org/opensearch/neuralsearch/transport/NeuralStatsNodeResponse.java
  src/main/java/org/opensearch/neuralsearch/transport/NeuralStatsRequest.java
  src/main/java/org/opensearch/neuralsearch/transport/NeuralStatsResponse.java
  src/main/java/org/opensearch/neuralsearch/transport/NeuralStatsTransportAction.java
  src/main/java/org/opensearch/neuralsearch/util/PipelineServiceUtil.java
  src/test/java/org/opensearch/neuralsearch/plugin/NeuralSearchTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/rest/RestNeuralStatsActionIT.java
  src/test/java/org/opensearch/neuralsearch/stats/NeuralStatsInputTests.java
  src/test/java/org/opensearch/neuralsearch/stats/events/EventStatNameTests.java
  src/test/java/org/opensearch/neuralsearch/stats/events/EventStatsManagerTests.java
  src/test/java/org/opensearch/neuralsearch/stats/events/TimestampedEventStatSnapshotTests.java
  src/test/java/org/opensearch/neuralsearch/stats/events/TimestampedEventStatTests.java
  src/test/java/org/opensearch/neuralsearch/stats/info/CountableInfoStatSnapshotTests.java
  src/test/java/org/opensearch/neuralsearch/stats/info/InfoStatNameTests.java
  src/test/java/org/opensearch/neuralsearch/stats/info/InfoStatsManagerTests.java
  src/test/java/org/opensearch/neuralsearch/stats/info/SettableInfoStatSnapshotTests.java
  src/test/java/org/opensearch/neuralsearch/transport/NeuralStatsResponseTests.java
  src/test/java/org/opensearch/neuralsearch/transport/NeuralStatsTransportActionTests.java
  src/test/java/org/opensearch/neuralsearch/util/PipelineServiceUtilTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: v3.0.0

#1233 Add remote-index-build-client dependency for k-NN
  build.gradle
  qa/build.gradle
Labels: Infrastructure, skip-changelog

#1224 Adds ZScore Normalization Technique
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  build.gradle
  src/main/java/org/opensearch/neuralsearch/processor/TechniqueCompatibilityCheckDTO.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ArithmeticMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/GeometricMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/HarmonicMeanScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/RRFScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombinationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/NormalizationProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/RRFNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ZScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/util/ProcessorUtils.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/ZScoreNormalizationTechniqueTests.java
Labels: Features, v3.0.0, hybrid search

#1230 Remove validation on text and image field for text_image_embedding processor
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessor.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorTests.java
Labels: bug, backport 2.x, backport 2.19

#1193 Support semantic sentence highlighter
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/highlight/SemanticHighlighter.java
  src/main/java/org/opensearch/neuralsearch/highlight/SemanticHighlighterEngine.java
  src/main/java/org/opensearch/neuralsearch/highlight/extractor/BooleanQueryTextExtractor.java
  src/main/java/org/opensearch/neuralsearch/highlight/extractor/HybridQueryTextExtractor.java
  src/main/java/org/opensearch/neuralsearch/highlight/extractor/NeuralQueryTextExtractor.java
  src/main/java/org/opensearch/neuralsearch/highlight/extractor/QueryTextExtractor.java
  src/main/java/org/opensearch/neuralsearch/highlight/extractor/QueryTextExtractorRegistry.java
  src/main/java/org/opensearch/neuralsearch/highlight/extractor/TermQueryTextExtractor.java
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/highlight/SentenceHighlightingRequest.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralKNNQuery.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralKNNQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/highlight/QueryTextExtractorTests.java
  src/test/java/org/opensearch/neuralsearch/highlight/SemanticHighlighterEngineTests.java
  src/test/java/org/opensearch/neuralsearch/highlight/SemanticHighlighterIT.java
  src/test/java/org/opensearch/neuralsearch/highlight/SemanticHighlighterTests.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralKNNQueryTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/resources/processor/UploadSentenceHighlightingModelRequestBody.json
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: neural-search, Features, v3.0.0

#1242 Fixed IT for Zscore
  src/test/java/org/opensearch/neuralsearch/highlight/SemanticHighlighterIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
Labels: skip-changelog

#1245 [3.0] Update neural-search for OpenSearch 3.0 beta compatibility
  CHANGELOG.md
  build.gradle
Labels: Maintenance, v3.0.0
