Repository opensearch-project/neural-search, pull requests merged in 2025-02, with the labels that each got.

#1157 [Release 3.0] Update gradle to 8.10.2 for JDK23 and codecov to v5 and fix delete backport branches
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/delete_backport_branch.yml
  .github/workflows/test_aggregations.yml
  .github/workflows/test_security.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: release, skip-changelog, v3.0.0

#1163 Add Release Notes for 2.19.0.0
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.19.0.0.md
Labels: backport 2.x, skip-changelog, v2.19.0, backport 2.19

#1167 Add release notes for 2.19
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-2.19.0.0.md
Labels: v2.19.0, backport 2.19

#1154 Handle exceptions gracefully when delete non-existent resources during integ test resource clean up
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/AbstractRestartUpgradeRestTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/AbstractRollingUpgradeTestCase.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralSparseTwoPhaseProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/RRFProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextChunkingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/ByFieldRerankProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryAggregationsIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryExplainIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryPostFilterIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/BucketAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/MetricAggregationsWithHybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/aggregation/PipelineAggregationsWithHybridQueryIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: good first issue, backport 2.x, Infrastructure, skip-changelog

#1178 code refactoring on MLCommonsClientAccessor request
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/main/java/org/opensearch/neuralsearch/processor/InferenceRequest.java
  src/main/java/org/opensearch/neuralsearch/processor/MapInferenceRequest.java
  src/main/java/org/opensearch/neuralsearch/processor/SimilarityInferenceRequest.java
  src/main/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/TextInferenceRequest.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessor.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/constants/TestCommonConstants.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/InferenceProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilderTests.java
Labels: Enhancements, help wanted, neural-search, skip-changelog, enhancement

#1183 Encapsulate KNNQueryBuilder creation within NeuralKNNQueryBuilder
  CHANGELOG.md
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/BatchIngestionIT.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralKNNQuery.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralKNNQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralKNNQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralKNNQueryTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
Labels: neural-search, Refactoring, v3.0.0

#1141 [3.0] Update neural-search for OpenSearch 3.0 compatibility
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/test_aggregations.yml
  CHANGELOG.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/AbstractRollingUpgradeTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/BatchIngestionIT.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/processor/rerank/RescoringRerankProcessor.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQuery.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryScorer.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryWeight.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralKNNQuery.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/search/HybridDisiWrapper.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridTopFieldDocSortCollector.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridTopScoreDocCollector.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/main/java/org/opensearch/neuralsearch/search/query/TopDocsMerger.java
  src/main/java/org/opensearch/neuralsearch/util/HybridQueryUtil.java
  src/test/java/org/opensearch/neuralsearch/processor/ExplanationResponseProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/RRFNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryExplainIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryScorerTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryWeightTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridScoreBlockBoundaryPropagatorTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralSparseQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/OpenSearchQueryTestCase.java
  src/test/java/org/opensearch/neuralsearch/search/collector/HybridTopFieldDocSortCollectorTests.java
  src/test/java/org/opensearch/neuralsearch/search/collector/HybridTopScoreDocCollectorTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridAggregationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridCollectorManagerTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/TopDocsMergerTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: Maintenance, Infrastructure

#502 Adding code guidelines
  DEVELOPER_GUIDE.md
Labels: Maintenance, skip-changelog

#1195 [Feature branch] Lower bounds for min-max normalization in hybrid query
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/CompoundTopDocs.java
  src/main/java/org/opensearch/neuralsearch/processor/factory/NormalizationProcessorFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/RRFNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationUtil.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/processor/CompoundTopDocsTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationUtilTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryExplainIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQuerySortIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/util/TestUtils.java
Labels: v3.0.0
