Repository opensearch-project/neural-search, pull requests merged in 2025-06, with the labels that each got.

#1358 Create a util class for chunking helper functions.
  src/main/java/org/opensearch/neuralsearch/processor/TextChunkingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/Chunker.java
  src/main/java/org/opensearch/neuralsearch/processor/semantic/SemanticFieldProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/util/ChunkUtils.java
  src/test/java/org/opensearch/neuralsearch/processor/util/ChunkUtilsTests.java
Labels: skip-changelog

#1364 Remove bwc test with window platform
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: skip-changelog

#1365 Update bwc test to use 3.1.0
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle.properties
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/RestNeuralStatsActionIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/RestNeuralStatsActionIT.java
Labels: skip-changelog

#1357 Use stack to collect semantic fields to avoid stack overflow
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/mappingtransformer/SemanticMappingTransformer.java
  src/main/java/org/opensearch/neuralsearch/util/SemanticMappingUtils.java
  src/test/java/org/opensearch/neuralsearch/util/SemanticMappingUtilsTests.java
Labels: skip-changelog

#1373 Fix stats BWC tests by filtering stats based on version
  CHANGELOG.md
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/RestNeuralStatsActionIT.java
  src/main/java/org/opensearch/neuralsearch/plugin/NeuralSearch.java
  src/main/java/org/opensearch/neuralsearch/rest/RestNeuralStatsAction.java
  src/main/java/org/opensearch/neuralsearch/stats/common/StatName.java
  src/main/java/org/opensearch/neuralsearch/stats/events/EventStatName.java
  src/main/java/org/opensearch/neuralsearch/stats/info/InfoStatName.java
  src/main/java/org/opensearch/neuralsearch/stats/info/InfoStatsManager.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/rest/RestNeuralStatsActionTests.java
  src/test/java/org/opensearch/neuralsearch/stats/info/InfoStatsManagerTests.java
Labels: bug

#1342 Feat: Add `FixedCharLengthChunker` for character length-based chunking
  CHANGELOG.md
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/RestNeuralStatsActionIT.java
  src/main/java/org/opensearch/neuralsearch/processor/TextChunkingProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/ChunkerFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/FixedCharLengthChunker.java
  src/main/java/org/opensearch/neuralsearch/stats/events/EventStatName.java
  src/main/java/org/opensearch/neuralsearch/stats/info/InfoStatName.java
  src/main/java/org/opensearch/neuralsearch/stats/info/InfoStatsManager.java
  src/test/java/org/opensearch/neuralsearch/processor/TextChunkingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextChunkingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/chunker/ChunkerFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/processor/chunker/FixedCharLengthChunkerTests.java
  src/test/resources/processor/chunker/PipelineForCascadedChunkerWithDelimiterAndFixedCharLength.json
  src/test/resources/processor/chunker/PipelineForCascadedChunkerWithDelimiterAndFixedTokenLength.json
  src/test/resources/processor/chunker/PipelineForFixedCharLengthChunker.json
Labels: v3.1.0

#1383 Fix ingest document wrapper constructor compilation errors in unit tests
  src/test/java/org/opensearch/neuralsearch/processor/InferenceProcessorTestCase.java
  src/test/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/semantic/SemanticFieldProcessorTests.java
Labels: skip-changelog, backport 3.1

#1382 Add release notes for 3.1.0
  CHANGELOG.md
  release-notes/opensearch-neural-search.release-notes-3.1.0.0.md
Labels: v3.1.0, backport 3.1

#1393 Fix neural radial search serialization in multi-node clusters
  qa/rolling-upgrade/build.gradle
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/KnnRadialSearchIT.java
  release-notes/opensearch-neural-search.release-notes-3.1.0.0.md
  src/main/java/org/opensearch/neuralsearch/common/MinClusterVersionUtil.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralKNNQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralKNNQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
Labels: bug, skip-changelog, backport 3.1

#1405 Fix the case where all subScorers are null
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryWeight.java
Labels: bug, skip-changelog

#1410 Use shared model across bwc tests
  qa/README.md
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/AbstractRestartUpgradeRestTestCase.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/BatchIngestionIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchWithRescoreIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/KnnRadialSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/MultiModalSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/NeuralQueryEnricherProcessorIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/NeuralSparseSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/NeuralSparseTwoPhaseProcessorIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/RestNeuralStatsActionIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/SemanticFieldIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/SemanticSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/AbstractRollingUpgradeTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/BatchIngestionIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/HybridSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/HybridSearchRelevancyIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/HybridSearchWithRescoreIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/KnnRadialSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/MultiModalSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/NeuralQueryEnricherProcessorIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/NeuralSparseSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/NeuralSparseTwoPhaseProcessorIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/RestNeuralStatsActionIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/SemanticFieldIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/SemanticSearchIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseUpgradeTestCase.java
Labels: Enhancements, skip-changelog

#1414 Fix the HybridQueryDocIdStream to properly handle upTo value
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStream.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryDocIdStreamTests.java
Labels: bug, flaky-test

#1413 Fix for collapse bug with knn query not deduplicating results
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactory.java
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridCollectorFactoryDTO.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/test/java/org/opensearch/neuralsearch/collector/HybridCollectorFactoryTests.java
  src/test/java/org/opensearch/neuralsearch/e2e/HybridCollapseIT.java
Labels: bug
