Repository opensearch-project/neural-search, pull requests merged in 2025-10, with the labels that each got.

#1591 Adding AgenticSearch remote model integration tests
  src/test/java/org/opensearch/neuralsearch/processor/AgenticQueryTranslatorProcessorRemoteModelIT.java
  src/test/java/org/opensearch/neuralsearch/query/AgenticSearchQueryBuilderRemoteModelIT.java
  src/test/resources/agenticsearch/AgenticSearchPipelineRequestBody.json
  src/test/resources/agenticsearch/CreateConnectorRequestBody.json
  src/test/resources/agenticsearch/RegisterAgentRequestBody.json
  src/test/resources/remote-models/torchserve/handlers/agentic_search_handler.py
  src/testFixtures/java/org/opensearch/neuralsearch/BaseAgenticSearchRemoteModelIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: skip-changelog

#1592 Add stats API for batch semantic highlighting
  src/main/java/org/opensearch/neuralsearch/highlight/batch/processor/SemanticHighlightingProcessor.java
  src/main/java/org/opensearch/neuralsearch/stats/events/EventStatName.java
  src/test/java/org/opensearch/neuralsearch/highlight/BaseSemanticHighlightingIT.java
  src/test/java/org/opensearch/neuralsearch/highlight/SemanticHighlightingLocalModelIT.java
  src/test/java/org/opensearch/neuralsearch/highlight/SemanticHighlightingRemoteModelIT.java
  src/test/resources/remote-models/torchserve/handlers/semantic_highlighter_handler.py
Labels: skip-changelog, v3.3.0

#1595 [Agentic Search] Fix rest error for agent execution
  src/main/java/org/opensearch/neuralsearch/processor/AgenticQueryTranslatorProcessor.java
  src/main/java/org/opensearch/neuralsearch/query/AgenticSearchQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/query/AgenticSearchQueryBuilderTests.java
Labels: bug, skip-changelog, agentic-search, backport 3.3
