Repository opensearch-project/neural-search, pull requests merged in 2025-01, with the labels that each got.

#1040 Fix bug where ingestion failed for input document containing list of nested objects
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
Labels: bug, backport 2.x, v2.19.0

#1055 Added runtime dependencies for jackson lib
  build.gradle
Labels: backport 2.x, Infrastructure, skip-changelog

#1043 Fixed document source and score field mismatch in sorted hybrid queries
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/search/collector/HybridTopFieldDocSortCollector.java
  src/test/java/org/opensearch/neuralsearch/search/collector/HybridTopFieldDocSortCollectorTests.java
  src/test/java/org/opensearch/neuralsearch/search/collector/HybridTopScoreDocCollectorTests.java
Labels: backport 2.x, Bug Fixes

#1054 Optimize ML inference connection retry logic
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessor.java
  src/main/java/org/opensearch/neuralsearch/util/RetryUtil.java
  src/test/java/org/opensearch/neuralsearch/ml/MLCommonsClientAccessorTests.java
Labels: Enhancements, help wanted, backport 2.x, v2.19.0

#1063 increase cluster node timeout value for time consuming test cases
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/BatchIngestionIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralSparseSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/SemanticSearchIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: bug, backport 2.x, skip-changelog

#1047 add support for builder constructor in neural query builder
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/KnnRadialSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralQueryEnricherProcessorIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/SemanticSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/KnnRadialSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/MultiModalSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/NeuralQueryEnricherProcessorIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/SemanticSearchIT.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/NeuralQueryEnricherProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreCombinationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/ScoreNormalizationIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/MLOpenSearchRerankProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/visitor/NeuralSearchQueryVisitorTests.java
Labels: backport 2.x, skip-changelog, v2.19.0

#1062 Fix bug where document embedding fails to be generated due to document has dot in field name
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/InferenceProcessor.java
  src/main/java/org/opensearch/neuralsearch/util/ProcessorDocumentUtils.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/util/ProcessorDocumentUtilsTests.java
  src/test/resources/processor/ingest_doc5.json
Labels: bug, backport 2.x

#1074 Clean up unused validateFieldName() and use existing methods for TextEmbeddingProcessorIT
  src/main/java/org/opensearch/neuralsearch/util/ProcessorDocumentUtils.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
Labels: backport 2.x, skip-changelog

#1075 Add reindex integration tests
  CHANGELOG.md
  src/test/java/org/opensearch/neuralsearch/processor/SparseEncodingProcessIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextChunkingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextEmbeddingProcessorIT.java
  src/test/java/org/opensearch/neuralsearch/processor/TextImageEmbeddingProcessorIT.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: good first issue, backport 2.x, Maintenance, Bug Fixes

#1079 Fix github CI by adding eclipse dependency in formatting.gradle
  CHANGELOG.md
  gradle/formatting.gradle
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
Labels: backport 2.x

#1045 Correct NeuralQueryBuilder doEquals() and doHashCode().
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/common/MinClusterVersionUtil.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/NeuralQueryBuilder.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/NeuralQueryBuilderTests.java
Labels: backport 2.x, v2.19.0

#1073 [Backport 2.x] add hybrid search with rescore IT (#1066)
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchWithRescoreIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/HybridSearchIT.java
Labels: skip-changelog

#1085 Renamed explanation response processor to hybrid_score_explanation
  src/main/java/org/opensearch/neuralsearch/processor/ExplanationResponseProcessor.java
  src/test/java/org/opensearch/neuralsearch/processor/factory/ExplanationResponseProcessorFactoryTests.java
Labels: backport 2.x, skip-changelog

#1048 Pagination in Hybrid query
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/common/MinClusterVersionUtil.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowExecuteRequest.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/CombineScoresDto.java
  src/main/java/org/opensearch/neuralsearch/processor/combination/ScoreCombiner.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQuery.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryContext.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcher.java
  src/main/java/org/opensearch/neuralsearch/util/HybridQueryUtil.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryWeightTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridAggregationProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridCollectorManagerTests.java
  src/test/java/org/opensearch/neuralsearch/search/query/HybridQueryPhaseSearcherTests.java
  src/test/java/org/opensearch/neuralsearch/util/HybridQueryUtilTests.java
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: backport 2.x

#1094 Update pagination_depth datatype from int to Integer
  src/main/java/org/opensearch/neuralsearch/query/HybridQuery.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryBuilder.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryContext.java
  src/main/java/org/opensearch/neuralsearch/search/query/HybridCollectorManager.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryBuilderTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryTests.java
Labels: skip-changelog

#1096 Use different package name between restart/rolling bwc tests
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/AbstractRestartUpgradeRestTestCase.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/BatchIngestionIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/HybridSearchWithRescoreIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/KnnRadialSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/MultiModalSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/NeuralQueryEnricherProcessorIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/NeuralSparseSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/NeuralSparseTwoPhaseProcessorIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/SemanticSearchIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/restart/TextChunkingProcessorIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/AbstractRollingUpgradeTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/BatchIngestionIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/HybridSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/HybridSearchWithRescoreIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/KnnRadialSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/MultiModalSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/NeuralQueryEnricherProcessorIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/NeuralSparseSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/NeuralSparseTwoPhaseProcessorIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/SemanticSearchIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/neuralsearch/bwc/rolling/TextChunkingProcessorIT.java
Labels: backport 2.x, Refactoring, skip-changelog

#1106 Enhance: Add comments to chunking-related code
  src/main/java/org/opensearch/neuralsearch/processor/chunker/Chunker.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/ChunkerFactory.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/ChunkerParameterParser.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/DelimiterChunker.java
  src/main/java/org/opensearch/neuralsearch/processor/chunker/FixedTokenLengthChunker.java
Labels: backport 2.x, skip-changelog

#969 ByField Rerank Improvements
  src/main/java/org/opensearch/neuralsearch/processor/rerank/ByFieldRerankProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/util/ProcessorUtils.java
  src/test/java/org/opensearch/neuralsearch/processor/rerank/ByFieldRerankProcessorTests.java
Labels: skip-changelog

#1110 Remove duplicate method call in NormalizationProcessorWorkflow
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
Labels: backport 2.x, skip-changelog, hybrid search

#1122 Fixed flaky integration test for explain in hybrid query
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryExplainIT.java
Labels: backport 2.x, skip-changelog, integ-test-failure, v2.19.0

#1121 Reverts Java 15 features from a backport to 2.x
  src/test/java/org/opensearch/neuralsearch/processor/rerank/ByFieldRerankProcessorTests.java
Labels: skip-changelog

#1128 Add check workflow events related checks
  .github/workflows/check-workflow-events.yml
Labels: Enhancements, skip-changelog

#1133 Always run check workflow events on all occasions
  .github/workflows/check-workflow-events.yml
Labels: Enhancements, backport 2.x, skip-changelog

#1130 Replaced upload api with register of ml commons
  src/testFixtures/java/org/opensearch/neuralsearch/BaseNeuralSearchIT.java
Labels: skip-changelog

#1123 Fix explain exception in hybrid queries with partial subquery matches
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/ExplanationResponseProcessor.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/RRFNormalizationTechnique.java
  src/main/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationUtil.java
  src/main/java/org/opensearch/neuralsearch/query/HybridQueryWeight.java
  src/test/java/org/opensearch/neuralsearch/processor/ExplanationResponseProcessorTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/L2ScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/MinMaxScoreNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/RRFNormalizationTechniqueTests.java
  src/test/java/org/opensearch/neuralsearch/processor/normalization/ScoreNormalizationUtilTests.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryExplainIT.java
  src/test/java/org/opensearch/neuralsearch/query/HybridQueryWeightTests.java
Labels: backport 2.x, Bug Fixes, v2.19.0

#1140 Fixed single shard pagination issue of from
  CHANGELOG.md
  src/main/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflow.java
  src/test/java/org/opensearch/neuralsearch/processor/NormalizationProcessorWorkflowTests.java
Labels: bug, backport 2.x, hybrid search, v2.19.0

#1147 Fixing integ tests due to missing opensearch-job-scheduler plugin and jayway lib
  build.gradle
  qa/build.gradle
Labels: backport 2.x, skip-changelog

#1158 Adding job scheduler dependency in bwc tests
  qa/build.gradle
  qa/restart-upgrade/build.gradle
  qa/rolling-upgrade/build.gradle
Labels: backport 2.x, skip-changelog, backport 2.19
